- name: Import kibana gpg key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: Add kibana Repo into source list 
  apt_repository: repo='deb http://packages.elastic.co/kibana/4.5/debian stable main' state=present

- name: Install kibana
  apt: name=kibana state=present update_cache=yes cache_valid_time=3600
  notify: init kibana

- name: Check kibana service
  service: name=kibana state=started enabled=yes
