---
- name: restart elasticsearch
  service: name=elasticsearch state=restarted enabled=yes
  
- name: init elasticsearch
  command: update-rc.d elasticsearch defaults 95 10
  notify: restart elasticsearch
